
name: Terraform

on:
  push:
    branches: [main]

jobs:
  terraform:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.0.0

      - name: Run localstack with docker
        run: docker run --rm -p 4566:4566 -p 4571:4571 localstack/localstack

      - name: Terraform Init
        run: terraform init

      - name: Terraform Apply
        run: terraform apply