name: Terraform

on:
  push:
    branches:
      - main

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker
        uses: actions/setup-docker@v1

      - name: Install Terraform
        uses: hashicorp/setup-terraform@v1

      - name: Start Localstack
        run: |
          docker run -d -p 4566:4566 -p 4571:4571 --name localstack localstack/localstack

      - name: Initialize Terraform
        run: terraform init
        working-directory: piaawch-2

      - name: Apply Terraform configuration
        run: terraform apply
        working-directory: piaawch-2